### ISSUE TITLE
`CTextInput` bugs

### ISSUE THREAD

**Issue by FilipeMarch** [kivy-school/kivy-widgets#10]
- [ ] Line mode + big font_size is bad
```yml
            CTextInput:
                mode: 'line'
                size_hint_x: .5
                hint_text: 'CTextInput'
                font_size: dp(32)
                pos_hint: {'center_x': .5, 'center_y': .5}
```
![image](https://github.com/kivy-school/kivy-widgets/assets/23220309/49371757-7fc4-40ff-b05f-fe2bcc0ad82e)

- [ ] Rectangle mode, hint text upwards has white background, but it should be "transparent", at the same time it covers the line behind it
![image](https://github.com/kivy-school/kivy-widgets/assets/23220309/77d351be-d656-4570-8c7b-e83a9f8fda45)

- [ ] Line mode, small text, with helper text. Helper text is too far away
![image](https://github.com/kivy-school/kivy-widgets/assets/23220309/6689d1f6-1565-4947-abd1-4b01e533d9de)

- [ ] Rectangle mode, small text, with helper text. Helper text is quite covering the TextInput
![image](https://github.com/kivy-school/kivy-widgets/assets/23220309/70f1d7c2-a8c8-4f09-93f6-21627891c5f8)
